# https://taskfile.dev

version: "3"

tasks:
  venv:
    summary: "install venv"
    cmds:
      - python3 -m venv venv

  install:
    summary: "install dependency"
    cmds:
      - pip3 install -r requirements.txt
  