# https://taskfile.dev

version: "3"

tasks:
  venv:
    summary: "install venv"
    cmds:
      - python3 -m venv venv

  install:
    summary: "install dependency"
    cmds:
      - pip3 install -r requirements.txt
  
  pull-model:
    cmds:
      - wget --output-document ./models/llma3.2-korean/llama-3.2-Korean-Bllossom-3B-gguf-Q4_K_M.gguf https://huggingface.co/Bllossom/llama-3.2-Korean-Bllossom-3B-gguf-Q4_K_M/resolve/main/llama-3.2-Korean-Bllossom-3B-gguf-Q4_K_M.gguf?download=true
      - ollama create llama3.2-korean -f ./models/llma3.2-korean/Modelfile

  run-model:
    cmds:
      - ollama run llama3.2-korean

  open-webui:
    summary: "Start Open WebUI server"
    cmds:
      - docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main